# Generated by Django 4.1.7 on 2023-03-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
