# Generated by Django 4.1.7 on 2023-04-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_comment_likes_alter_profile_dob_alter_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='post_comments', to='MainApp.comment'),
        ),
    ]
