# Generated by Django 4.1.7 on 2023-05-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_remove_profile_followers_remove_profile_following_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
    ]
